version: '3'

networks:
  frontend:
services:
  app:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '${DC_APP_PORT:-80}:80'
    env_file:
      - .env
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - node
  node:
    env_file:
      - .env
    image: node:current-alpine
    ports:
        - '${DC_NODE_PORT:-3000}:3000'
    stdin_open: true
    volumes:
      - ./:/var/www/html:delegated
    working_dir: /var/www/html
    networks:
      - frontend